### PR TITLE
Use mm/s

### LINKED ISSUE #114: Check speed units
RU sends calculates speed in steps/s, however DCS should work with mm/s.

Check if this is correctly implemented and fix otherwise.

### PR DESCRIPTION
**Pull request by gabryelreyes**
Use mm/s instead of steps/s
Allows for the counterpart to use SI units instead of steps.
Counterpart of https://github.com/BlueAndi/RadonUlzer/pull/146

Closes #114

### CODE REVIEW

**Comment by nhjschulz** [comment]
Would have been a good oportunity to introduce a user type for speed, something like typedef uint32_t velocity_t.

**Comment by BlueAndi** [comment]
The change has influence on the PIDs, I only saw one change there. What about calculations at all?

**Comment by gabryelreyes** [comment]
I tested the simulation and this was the only change required for the stability of the platoon

**Comment by BlueAndi** [comment]
> I tested the simulation and this was the only change required for the stability of the platoon

A stability issue means there is a bug or bad parameters. There is no influence just by unit change on stability. ;-)
Anyway you can merge, but the stability issue might still be included and just damped.

**Review by BlueAndi — APPROVED** [review]

**Comment by gabryelreyes** [comment]
Not even an issue when the maximum value possible changes? Then you may be right, and there may still be an issue

**Comment by BlueAndi** [comment]
> Not even an issue when the maximum value possible changes?

No, there is always a max. speed by electronic + mechanic. Every higher value is limited on RU side. Seems for me the problem is on DCS side, that it assumes the higher speed will work, but it doesn't.

**Pull request merged**
